apiVersion: v1
kind: Namespace
metadata:
  name: enterprise

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: enterprise
type: Opaque
stringData:
  host: "enterprise-rds-db.385168913795.ap-south-1.rds.amazonaws.com"
  port: "3306"
  username: "adminuser"
  password: "ChangeMe123!"
  database: "appdb"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: enterprise
data:
  NODE_ENV: "production"
  PORT: "4000"
