name: CI/CD Pipeline

permissions:
  contents: write
  id-token: write

on:
  push:
    branches:
      - main
      - master
      - develop

  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  test-build:
    name: Backend + Frontend Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [backend, frontend]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: |
            apps/backend/package-lock.json
            apps/frontend/package-lock.json

      - name: Install backend dependencies
        if: matrix.service == 'backend'
        working-directory: apps/backend
        run: npm install

      - name: Install frontend dependencies
        if: matrix.service == 'frontend'
        working-directory: apps/frontend
        run: npm install

      - name: Run backend tests
        if: matrix.service == 'backend'
        working-directory: apps/backend
        run: npm test -- --passWithNoTests

      - name: Run frontend tests
        if: matrix.service == 'frontend'
        working-directory: apps/frontend
        env:
          CI: true
        run: npm test -- --watchAll=false --passWithNoTests

      - name: Build frontend
        if: matrix.service == 'frontend'
        working-directory: apps/frontend
        run: npm run build

  build-push-ecr:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: test-build

    if: github.event_name == 'push'

    env:
      AWS_REGION: ap-south-1
      ECR_REGISTRY: 385168913795.dkr.ecr.ap-south-1.amazonaws.com

      BACKEND_REPO: backend-ecr-repo
      FRONTEND_REPO: frontend-ecr-repo

      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Ensure Backend ECR Repo Exists
        run: |
          aws ecr describe-repositories --repository-names $BACKEND_REPO || aws ecr create-repository --repository-name $BACKEND_REPO

      - name: Ensure Frontend ECR Repo Exists
        run: |
          aws ecr describe-repositories --repository-names $FRONTEND_REPO || aws ecr create-repository --repository-name $FRONTEND_REPO

      - name: Build Backend Docker Image
        run: |
          docker build \
          -t $ECR_REGISTRY/$BACKEND_REPO:$IMAGE_TAG \
          -t $ECR_REGISTRY/$BACKEND_REPO:latest \
          -f apps/backend/Dockerfile apps/backend

      - name: Push Backend Docker Image
        run: |
          docker push $ECR_REGISTRY/$BACKEND_REPO:$IMAGE_TAG
          docker push $ECR_REGISTRY/$BACKEND_REPO:latest

      - name: Build Frontend Docker Image
        run: |
          docker build \
          -t $ECR_REGISTRY/$FRONTEND_REPO:$IMAGE_TAG \
          -t $ECR_REGISTRY/$FRONTEND_REPO:latest \
          -f apps/frontend/Dockerfile apps/frontend

      - name: Push Frontend Docker Image
        run: |
          docker push $ECR_REGISTRY/$FRONTEND_REPO:$IMAGE_TAG
          docker push $ECR_REGISTRY/$FRONTEND_REPO:latest

      - name: Update Kubernetes Manifests
        run: |
          sed -i "s|image: .*|image: $ECR_REGISTRY/$BACKEND_REPO:$IMAGE_TAG|g" kubernetes/02-backend-deployment.yaml

      - name: Commit and Push Updated Manifest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add kubernetes/02-backend-deployment.yaml

          git commit -m "Updated backend image to $IMAGE_TAG" || echo "No changes"

          git push